### ISSUE TITLE
add mutlilingual support (concept tables) for pycube

### ISSUE THREAD

**Issue by CDiGallo** [Kronmar-Bafu/pylindas#21]
A lot of .csvs have colums "canton" "year" "typeOfAirport_en" "typeOfAirport_de" "typeOfAirport_fr".

in Cube creator you can add these 3 columns in one column but every row has 3 values. one for every language. 
This feature should be in pycube as well.

in Pycube there needs a new method. This is controlled via yaml-file. (update yaml-file in wiki). 

Check if pycube.write_observation or pycube.wirite_shape (or other methods) get confused and produce bugs, because it makes for every column in the pandas a new feature-shape.

**Comment by Kronmar-Bafu** [comment]
Here a first suggestion for implementation:

**Target**
So, what we would like to have is something along this line here, right?
```turtle
<cube_uri/observations/obs_id> <base_uri/typeOfAirport> <base_uri/TypeOfAirport/A> .

<base_uri/TypeOfAirport/A> schema:name "Inlandflughafen"@de, "domestic airport"@en, "aéroport intérieur"@fr, "aeroporto interno"@it . 
```

**Implementation**
The data (from `.csv` or else) looks like:
```csv
id,some_measure,canton,year,typeOfAirport_en,typeofAirport_de,typeOfAirport_fr
...
817,12,BE,2001,domestic airport,Inlandflughafen,aéroport intérieur
...
```

The information stored in `typeOfAirport_de` and `typeOfAirport_fr` is (hopefully!) redundant. The `description.yml` could look like:

```yaml
dimensions:
  typeOfAirport_en:
    name:
      de: Flughafentyp
      en: Type of Airport
      fr: Type d'aéroport
      it: Tipo di aeroporto
    scale-type: nominal
    path: typeOfAirport
    mapping:
      type: replace
      replacements:
        domestic airport:
          path: https://mock.ld.admin.ch/typeOfAirport/domesticAirport
          name: 
            de: Inlandflughafen
            fr: aéroport intérieur
            it: aeroporto interno
            en: domestic airport
```
So basically, the existing functionality for the mapping type `replace` get's extended. 

The other columns in the input `csv` are simply ignored. Of course there should be a check for redundancy in `typeOfAirport_de` and `typeOfAirport_fr`, i.e. are the columns consistent with one another)

Pros and Cons:
(+) Everything remains in the yaml
(-) yaml might get "wordy"

An alternative could be to have an aditional `concepts.yml` file. Might be cleaner? And it could be somewhat generic to guarantee reusability?

An example `concepts.yml` could look like
```yaml
Concepts:
  base_uri: https://mock.ld.admin.ch/ #to guarantee the user only writes to his graph
  Types of Airports:
    domestic airport:
      name: 
        de: Inlandflughafen
        fr: aéroport intérieur
        it: aeroporto interno
        en: domestic airport
```
The `description.yml` would then simplify to:
```yaml
dimensions:
  typeOfAirport_en:
    path: typeOfAirport
    mapping:
      type: replace
      replacements:
        domestic airport: base_uri/TypeOfAirport/A
```

**Comment by Kronmar-Bafu** [comment]
Other option, without writing a URI


```turtle
dimensions:
  typeOfAirport_en:
    name:
      de: Flughafentyp
      en: Type of Airport
      fr: Type d'aéroport
      it: Tipo di aeroporto
    scale-type: nominal
    path: typeOfAirport
    translations:
      domestic airport:
        de: Inlandflughafen
        fr: aéroport intérieur
        it: aeroporto interno
       en: domestic airport
```

**Comment by FabianCretton** [comment]
After a nice live talks with @Kronmar-Bafu about this, I do have a first question before talking about the .yaml structure:
- With reference to how this is handled in the Cube Creator, does PyCube already handle so called "Concept" tables ? This is described [here ](https://github.com/zazuko/cube-creator/wiki/1.-CSV-Mapping#concept-table-1) in the CC help, and[ just under](https://github.com/zazuko/cube-creator/wiki/1.-CSV-Mapping#language-and-translations) is described the way to handle translations).  
And thus, before talking about translations themselves, how do you currently handle Cubes with multiple CSV in input (one CSV per concept). This is a very common case in the datasets I have worked on.
Note: It could happen that the concepts are in the same CSV as the cube data, but then with a lot of redundancies (which is ok, I saw this in some datasets and I give an example here under).

Moving next, we see that Marco's proposal makes totally sense: for Visualize to interpret correctly the translations, a new concept has to be created, that is a resource in RDF, with its own URL, and the translations are schema:name values for it (with the language strings as object, as in his example here above).  
This means that the object of the dimension is not a string, but a concept. We therefore need a way to find a key for that concept and build its URL. 

Working with the Cube Creator over the years, I have seen the different situations that I describe here:

If the concept values is in another CSV, than this key certainly exists to link the values of the two files, example:
**cubeData.csv**:
```
id,some_measure,canton,year,typeOfAirport
...
817,12,BE,2001,A
818,15,GE,2001,A
819,19,BE,2001,B
820,23,GE,2001,B
...
```
**airportType.csv**:
```
typeOfAirportID,typeOfAirport_en,typeofAirport_de,typeOfAirport_fr
...
A,domestic airport,Inlandflughafen,aéroport national
B,international airport,Internationaler Flughafen,aéroport international 
...
```
If the concept values are in the same CSV, than their might be a column with the key:
**cubeData_allInOne_withTypeOfAirportID.csv**:
```
id,some_measure,canton,year,typeOfAirportID,typeOfAirport_en,typeofAirport_de,typeOfAirport_fr
...
817,12,BE,2001,A,domestic airport,Inlandflughafen,aéroport national
818,15,GE,2001,A,domestic airport,Inlandflughafen,aéroport national
819,19,BE,2001,B,international airport,Internationaler Flughafen,aéroport international 
820,23,GE,2001,B,international airport,Internationaler Flughafen,aéroport international 
...
```
And it could finally happen (do we allow it ?), that there is not identifier, as in the original example from Claudio:
**cubeData_allInOne_noTypeOfAirportID.csv**:
```
id,some_measure,canton,year,typeOfAirport_en,typeofAirport_de,typeOfAirport_fr
...
817,12,BE,2001,domestic airport,Inlandflughafen,aéroport national
818,15,GE,2001,domestic airport,Inlandflughafen,aéroport national
819,19,BE,2001,international airport,Internationaler Flughafen,aéroport international 
820,23,GE,2001,international airport,Internationaler Flughafen,aéroport international 
...
```
In that last case, one of the translation could be use to create the URL (url encode of the string), which also means that the value for that translation is mandatory on all lines.

To be noted that this is very similar to Shared Dimension handling (Shared Dimension was always in my mind a synonym to "linked data", basically linking resources between them, also resources from other datasets -> linked data).  

Please let me know you input about this, and then we can think about the needed .yaml (going further with Marco's proposal), right ?

**Comment by FabianCretton** [comment]
I go on with my thoughts about handling multiple files (the so called "concept tables" in Cube Creator), and applying this to handle the multilingual dimensions. This could also serve as input/discussion about the handling of Shared Dimensions.  

If there is no notion of handling multiple files in the current PyCube (my comment here above from yesterday), here is a first proposal to handle all of this: multiple files and multilingual.

Same example with two files:
cubeData.csv:
```
id,some_measure,canton,year,typeOfAirport
...
817,12,BE,2001,A
818,15,GE,2001,A
819,19,BE,2001,B
820,23,GE,2001,B
...
```
airportType.csv:

```
typeOfAirportID,typeOfAirport_en,typeofAirport_de,typeOfAirport_fr
...
A,domestic airport,Inlandflughafen,aéroport national
B,international airport,Internationaler Flughafen,aéroport international 
...
```
The link between the two files is voluntarily based on fields with different names: typeOfAirport/typeOfAirportID. 

Here first a proposal to handle the concept-tables, simply adding one entry per file under a specific node, for instance "concept-tables":
```
concept-tables:
	concept_airport_types:
		file: airport_types.csv
		URI: https://mock.ld.admin.ch/airport_type/{typeOfAirportID}
		nameField: typeOfAirport
		multilingual: true 
```
Explanation:
- `URI`: maybe you have other ways to do it in PyCube, but here I take the form of URL used in CubeCreator, with a fixed URL that will be completed with a CSV field, `{typeOfAirportID}` in that example.
- `nameField`: in concept tables, a name is mandatory (will be schema:name). Here the name is taken from the CSV field `typeOfAirport`  
Note: the values for name are not in the .yaml file, but in the CSV itself.
- `multilingual`: true/false. 
If multilingual is False, than a single schema:name is added, with the value of the `nameField`field. 
If multilingual is True, we handle the multilingual values, looking for fields names `nameField`with the suffixes "_en", "_de", "_fr", etc.

Then about the dimension that links to that concept-table, I base my proposal on Marco's proposal here above:
```
dimensions:
  typeOfAirport:
    name:
      de: Flughafentyp
      en: Type of Airport
      fr: Type d'aéroport
      it: Tipo di aeroporto
    scale-type: nominal
    mapping:
      type: concept
      replacement: https://mock.ld.admin.ch/airport_type/{typeOfAirport}
```
Explanation:
- `name`: this is the name of the dimension as for other dimensions
- `scale-type`: nominal as usually for so-called concepts (see CC help [here](https://github.com/zazuko/cube-creator/wiki/3.-Cube-Designer#scale-of-measure))
- `mapping/type`: concept to indicate that it will be a replacement based on a field
- `mapping/replacement`: how to build the URL based on the CSV field `{typeOfAirport}`. Maybe I am wrong, but I could think that we could either have the `replacements `(with an 's') and indicating all the correspondances, or a single `replacement `(no 's'), and indicate how to build the URLs.

As I am new to the PyCube, I do not know if I propose things that are already solved in another way, thank you for the discussion. I will not implement anything before we come to an agreement.

**Comment by Kronmar-Bafu** [comment]
> * With reference to how this is handled in the Cube Creator, does PyCube already handle so called "Concept" tables ? This is described [here ](https://github.com/zazuko/cube-creator/wiki/1.-CSV-Mapping#concept-table-1) in the CC help, and[ just under](https://github.com/zazuko/cube-creator/wiki/1.-CSV-Mapping#language-and-translations) is described the way to handle translations).

There is currently no implementation in `pyCube` for concept tables.

>   And thus, before talking about translations themselves, how do you currently handle Cubes with multiple CSV in input (one CSV per concept). This is a very common case in the datasets I have worked on.

What we have here now, is completely new indeed. Your suggestions for structure in yaml file looks good to me. What I would envision here is something like `cube = pyCube.Cube(dataframe, cube_yaml, concepts_dataframe)`.  This `concepts_dataframe`  would be a second dataframe containing the concepts. This dataframe contains some key and the translations as a minimum. An optional description and a position (like in CC) should be supported as well. 
Quick remark on that: [the IRI created for these concepts are `cube:Cube` specific](https://s.zazuko.com/2UgaWYc). While I don't like that way as it contradicts the idea of *linked* data, I see why it was solved like that, as it strictly keeps even parts (that is versions) of the same `schema:WorkExample` apart from one another.

Keeping with this philosophie (something open for debate!), we should change the yaml slightly

```yaml
dimensions:
  typeOfAirport:
    name:
      de: Flughafentyp
      en: Type of Airport
      fr: Type d'aéroport
      it: Tipo di aeroporto
    scale-type: nominal
    mapping:
      type: concept
      key: typeOfAirport
```

This would disentangle two separate things: IRI which are `cube:Cube`-specific (so even depend on version) and `meta:SharedDimension` which are not specific to a specific cube. The `schema:name` are then provided by the concept dataframe.


As for the case of everything being in the same dataframe, I'm not yet sure how to handle that case. We could simply dissallow such a thing to be passed to `pyCube.Cube()`. But in that case we should implement some utility functions in `pylindas.lindas` to help the user prepare data for such a case?
